# Generated by Django 4.2.3 on 2023-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_qty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partqty',
            name='canceledBy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partqty',
            name='canceledDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
