# Generated by Django 4.2.3 on 2023-08-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_companyid'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('message', models.TextField(default=None)),
                ('phoneNumber', models.CharField(default=None, max_length=200, null=True)),
                ('canceledBy', models.IntegerField(null=True)),
                ('canceledDateTime', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelable', models.BooleanField(default=True)),
                ('createdBy', models.BigIntegerField()),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
