# Generated by Django 4.2.3 on 2023-07-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('partId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('payPaltoken', models.CharField(max_length=200, null=True)),
                ('canceledBy', models.IntegerField(null=True)),
                ('canceledDateTime', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelable', models.BooleanField()),
                ('createdBy', models.BigIntegerField()),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('unitCost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('partType', models.CharField(max_length=50, null=True)),
                ('imageFile', models.CharField(max_length=512, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('subcategory', models.CharField(max_length=50, null=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='partTran',
            fields=[
                ('partTranId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tranQty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tranType', models.CharField(max_length=50)),
                ('canceledBy', models.IntegerField(null=True)),
                ('canceledDateTime', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelable', models.BooleanField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.part')),
            ],
        ),
        migrations.CreateModel(
            name='partQty',
            fields=[
                ('partQtyId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('onHandQty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('canceledBy', models.IntegerField(null=True)),
                ('canceledDateTime', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelable', models.BooleanField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.part')),
            ],
        ),
    ]
