# Generated by Django 4.2.3 on 2023-08-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_alter_part_partid_alter_partqty_partqtyid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='partQty',
        ),
    ]
