# Generated by Django 4.2.3 on 2023-08-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
