# Generated by Django 4.2.3 on 2023-08-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_companyid'),
        ('part', '0003_delete_partqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTotal', models.CharField(max_length=200, null=True)),
                ('taxes', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('total', models.DecimalField(decimal_places=4, default=None, max_digits=18)),
                ('totalLetter', models.TextField(default=None)),
                ('currencyNum', models.CharField(default=None, max_length=100, null=True)),
                ('closedBy', models.BigIntegerField(default=0)),
                ('closedDateTime', models.DateTimeField(default=None)),
                ('payed', models.DecimalField(decimal_places=4, default=None, max_digits=18)),
                ('change', models.DecimalField(decimal_places=4, default=None, max_digits=18)),
                ('closed', models.BooleanField(default=None)),
                ('customerEmail', models.EmailField(default=None, max_length=254)),
                ('canceledBy', models.IntegerField(null=True)),
                ('canceledDateTime', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelable', models.BooleanField()),
                ('createdBy', models.BigIntegerField()),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('unitCost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('partType', models.CharField(max_length=50, null=True)),
                ('imageFile', models.CharField(max_length=512, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('subcategory', models.CharField(max_length=50, null=True)),
                ('isWebOrder', models.BooleanField(default=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='salesOrderDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('salesOrderQty', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('canceledBy', models.IntegerField(null=True)),
                ('canceledDateTime', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('unitPrice', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('taxesPerUnit', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('totalTaxes', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('total', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('cancelable', models.BooleanField()),
                ('discount', models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True)),
                ('partRev', models.IntegerField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.part')),
                ('salesOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesOrder.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='paymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(default=None, max_length=50, null=True)),
                ('fullName', models.CharField(default=None, max_length=200, null=True)),
                ('addressLine1', models.CharField(default=None, max_length=500, null=True)),
                ('addressLine2', models.CharField(default=None, max_length=500, null=True)),
                ('adminArea1', models.CharField(default=None, max_length=200, null=True)),
                ('adminArea2', models.CharField(default=None, max_length=200, null=True)),
                ('postalCode', models.CharField(default=None, max_length=50, null=True)),
                ('countryCode', models.CharField(default=None, max_length=50, null=True)),
                ('orderStatus', models.CharField(default=None, max_length=75, null=True)),
                ('externalOrderId', models.CharField(default=None, max_length=100, null=True)),
                ('orderIntent', models.CharField(default=None, max_length=100, null=True)),
                ('orderLinks', models.CharField(default=None, max_length=2000, null=True)),
                ('orderCreated', models.CharField(default=None, max_length=200, null=True)),
                ('salesOrderId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salesOrder.salesorder')),
            ],
        ),
    ]
