from django.db import models
from company.models import company
from part.models import part

# Create your models here.
class salesOrder(models.Model):
    companyId = models.ForeignKey(company, on_delete=models.CASCADE)
    subTotal = models.CharField(max_length=200, null=True)
    taxes = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    total = models.DecimalField(max_digits=18, decimal_places=4, default=None)
    totalLetter = models.TextField(default=None)
    currencyNum = models.CharField(max_length=100, null=True, default=None)
    closedBy =  models.BigIntegerField(null=False, default=0)
    closedDateTime = models.DateTimeField(auto_now_add=False, default=None)
    payed = models.DecimalField(max_digits=18, decimal_places=4, default=None)
    change = models.DecimalField(max_digits=18, decimal_places=4, default=None)   
    closed = models.BooleanField(default=None)
    customerEmail =  models.EmailField(default=None)
    canceledBy = models.IntegerField(null=True)
    canceledDateTime = models.DateTimeField(null=True)
    canceled = models.BooleanField(default=False)
    cancelable = models.BooleanField()
    createdBy = models.BigIntegerField()
    createdDateTime = models.DateTimeField(auto_now_add=True)
    unitCost = models.DecimalField(max_digits=18, decimal_places=2)
    partType = models.CharField(max_length=50, null=True)
    imageFile = models.CharField(max_length=512, null=True)
    category = models.CharField(max_length=50, null=True)
    subcategory = models.CharField(max_length=50, null=True)
    isWebOrder = models.BooleanField(default=True)


class paymentData(models.Model):
    salesOrderId =  models.OneToOneField(salesOrder, on_delete=models.CASCADE)
    paymentType = models.CharField(max_length=50,null=True, default=None)   
    fullName = models.CharField(max_length=200, null=True, default=None)
    addressLine1 = models.CharField(max_length=500, null=True, default=None)
    addressLine2 = models.CharField(max_length=500, null=True, default=None)
    adminArea1 = models.CharField(max_length=200, null=True, default=None)
    adminArea2 = models.CharField(max_length=200, null=True, default=None)
    postalCode = models.CharField(max_length=50, null=True, default=None)
    countryCode = models.CharField(max_length=50, null=True, default=None)
    orderStatus = models.CharField(max_length=75, null=True, default=None)
    externalOrderId = models.CharField(max_length=100, null=True, default=None)
    orderIntent = models.CharField(max_length=100, null=True, default=None)
    orderLinks = models.CharField(max_length=2000, null=True, default=None)
    orderCreated = models.CharField(max_length=200, null=True, default=None)
 
class salesOrderDtl(models.Model):
    companyId = models.ForeignKey(company,on_delete=models.CASCADE, null=False)
    salesOrderId = models.ForeignKey(salesOrder,on_delete=models.CASCADE, null=False)
    line = models.IntegerField(null=False)
    partId = models.ForeignKey(part,on_delete=models.CASCADE, null=False)
    salesOrderQty = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    canceledBy = models.IntegerField(null=True)
    canceledDateTime = models.DateTimeField(null=True)
    canceled = models.BooleanField(default=False)
    unitPrice = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    taxesPerUnit = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    totalTaxes = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    total = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    cancelable = models.BooleanField()
    discount = models.DecimalField(max_digits=18, decimal_places=4 ,null=True, default=None)
    partRev = models.IntegerField(null=False)    